languageCode = "en"
languageName = "English"
weight = 1
title = "Imran Ali"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/blowfish_logo_transparent.png"
  # secondaryLogo = "PATH"
  description = "Imran Ali"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Imran Ali"
  image = "img/imranhs2.png"
  headline = "DevOps | Cloud | Platform Eng"
  bio = "A curious human learning as he grows."
  links = [
    { linkedin = "https://www.linkedin.com/in/imranali-devops/" },
    { github = "https://github.com/imranalley" },
    { email = "mailto:imranrali1@gmail.com"}
  ]

  